### ISSUE TITLE
Trying to setup constraints and indexes

### ISSUE THREAD

**Issue by dangourary** [neo4j-contrib/django-neomodel#14]
Hey there I'm trying to create a new project on Django and to connect it to Neo4J.
I'm a kind of nooby in Neo4J, had some expirience with Django :)
I created two types of nodes Person and Country and tried to add the constraints or indexes need to be added to Neo4j
I'm not sure that I ran the correct commend

neomodel_install_labels neomodel_init.py someapp.models --db bolt://neo4j:
Traceback (most recent call last):
  File "/home/dan/Python_Environments/django_neomodel/bin/neomodel_install_labels", line 67, in <module>
    main()
  File "/home/dan/Python_Environments/django_neomodel/bin/neomodel_install_labels", line 58, in main
    load_python_module_or_file(app)
  File "/home/dan/Python_Environments/django_neomodel/bin/neomodel_install_labels", line 30, in load_python_module_or_file
    import_module(module_name, package=pkg)
  File "/home/dan/Python_Environments/django_neomodel/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'neomodel_init'

**Comment by adriancarayol** [comment]
Have you tried the following command?

`python manage.py install_labels`
