### ISSUE TITLE
Issue with connecting

### ISSUE THREAD

**Issue by mnagler-brandeis** [neo4j-contrib/django-neomodel#23]
Hi, I have a neo4j database running on `localhost:7687`, called "test_db." 
The neo4j user has a password, let's just say it's "password." 

I added the following code to the settings.py file in my Django project. 
```python
from neomodel import config
config.DATABASE_URL = 'bolt://neo4j:password@localhost:7687'
```

When I go to run `python manage.py install_labels` I get the following error:
`ValueError: Invalid IP address 'fe80::1%lo0'`

I know that a similar issue was posted a while ago, but the solution to that error was to remove special characters from the password. My password only includes letters and numbers. 

I don't know if it matters, but within this project there is an already existing app with a Postgres database. I'm setting up a second app which will be using a neo4j database. 

The full stack trace is:
```
Found trajectory.models.Person
 + Creating unique constraint for name on label Person for class trajectory.models.Person
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/michaelnagler/klausen_lab/work_station/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/Users/michaelnagler/klausen_lab/work_station/lib/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/michaelnagler/klausen_lab/work_station/lib/python2.7/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/michaelnagler/klausen_lab/work_station/lib/python2.7/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/Users/michaelnagler/klausen_lab/work_station/lib/python2.7/site-packages/django_neomodel/management/commands/install_labels.py", line 12, in handle
    install_all_labels(stdout=self.stdout)
  File "/Users/michaelnagler/klausen_lab/work_station/lib/python2.7/site-packages/neomodel/core.py", line 125, in install_all_labels
    install_labels(cls, quiet=False, stdout=stdout)
  File "/Users/michaelnagler/klausen_lab/work_station/lib/python2.7/site-packages/neomodel/core.py", line 102, in install_labels
    cls.__label__, db_property))
  File "/Users/michaelnagler/klausen_lab/work_station/lib/python2.7/site-packages/neomodel/util.py", line 31, in wrapper
    _db.set_connection(config.DATABASE_URL)
  File "/Users/michaelnagler/klausen_lab/work_station/lib/python2.7/site-packages/neomodel/util.py", line 65, in set_connection
    max_pool_size=config.MAX_POOL_SIZE)
  File "/Users/michaelnagler/klausen_lab/work_station/lib/python2.7/site-packages/neo4j/v1/api.py", line 128, in driver
    return driver_class(uri, **config)
  File "/Users/michaelnagler/klausen_lab/work_station/lib/python2.7/site-packages/neo4j/v1/direct.py", line 77, in __init__
    pool.release(pool.acquire())
  File "/Users/michaelnagler/klausen_lab/work_station/lib/python2.7/site-packages/neo4j/v1/direct.py", line 47, in acquire
    connection = self.acquire_direct(address)  # should always be a resolved address
  File "/Users/michaelnagler/klausen_lab/work_station/lib/python2.7/site-packages/neo4j/bolt/connection.py", line 427, in acquire_direct
    raise ValueError("Invalid IP address {!r}".format(address[0]))
ValueError: Invalid IP address 'fe80::1%lo0'
```

**Comment by adriancarayol** [comment]
Hi, are you try with neo4j password?

Greetings.

**Comment by mnagler-brandeis** [comment]
I'm using the password I created when I set up my neo4j database.
I even tried adding a new user to the database and that wouldn't work either.

**Comment by adriancarayol** [comment]
Try with this:

NEOMODEL_NEO4J_BOLT_URL = 'bolt://neo4j:password@localhost:7687')

**Comment by mnagler-brandeis** [comment]
Thank you for the speedy responses. I have tried the above suggestion and it is not working, same error.

**Comment by adriancarayol** [comment]
Hmm... Maybe using Python 3 instead python 2...

**Comment by mnagler-brandeis** [comment]
Hmm... that would require updating the entire project to python 3, no?

**Comment by adriancarayol** [comment]
Yes, but you can create a new project (only for testing) un python3

**Comment by mnagler-brandeis** [comment]
Ok. I'll give that a shot and see what happens

**Comment by jyxe** [comment]
Hi, I just want to connect the graph database of Neo4j. Can you tell me how to config the settings.py?
