### ISSUE TITLE
Migrations fail 

### ISSUE THREAD

**Issue by faramarza** [neo4j-contrib/django-neomodel#29]
Trying to get this working but as soon as I add the following to my settings.py

NEOMODEL_NEO4J_BOLT_URL = os.environ.get('NEO4J_BOLT_URL', 'bolt://neo4j:test@localhost:7687')

INSTALLED_APPS = (
    # django.contrib.auth etc
    'django_neomodel',
    'yourapp'
)

I get an error in migrations... can not move on ... here is the error:

python manage.py showmigrations
Traceback (most recent call last):
  File "C:\Users\dcrom\PycharmProjects\dgv02\venv\lib\site-packages\django\apps\registry.py", line 152, in get_app_config
    return self.app_configs[app_label]
KeyError: 'admin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\dcrom\PycharmProjects\dgv02\venv\lib\site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "C:\Users\dcrom\PycharmProjects\dgv02\venv\lib\site-packages\django\core\management\__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\dcrom\PycharmProjects\dgv02\venv\lib\site-packages\django\core\management\base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\dcrom\PycharmProjects\dgv02\venv\lib\site-packages\django\core\management\base.py", line 350, in execute
    self.check()
  File "C:\Users\dcrom\PycharmProjects\dgv02\venv\lib\site-packages\django\core\management\base.py", line 379, in check
    include_deployment_checks=include_deployment_checks,
  File "C:\Users\dcrom\PycharmProjects\dgv02\venv\lib\site-packages\django\core\management\base.py", line 366, in _run_checks
    return checks.run_checks(**kwargs)
  File "C:\Users\dcrom\PycharmProjects\dgv02\venv\lib\site-packages\django\core\checks\registry.py", line 71, in run_checks
    new_errors = check(app_configs=app_configs)
  File "C:\Users\dcrom\PycharmProjects\dgv02\venv\lib\site-packages\django\core\checks\urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "C:\Users\dcrom\PycharmProjects\dgv02\venv\lib\site-packages\django\core\checks\urls.py", line 23, in check_resolver
    return check_method()
  File "C:\Users\dcrom\PycharmProjects\dgv02\venv\lib\site-packages\django\urls\resolvers.py", line 396, in check
    for pattern in self.url_patterns:
  File "C:\Users\dcrom\PycharmProjects\dgv02\venv\lib\site-packages\django\utils\functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\dcrom\PycharmProjects\dgv02\venv\lib\site-packages\django\urls\resolvers.py", line 533, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Users\dcrom\PycharmProjects\dgv02\venv\lib\site-packages\django\utils\functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\dcrom\PycharmProjects\dgv02\venv\lib\site-packages\django\urls\resolvers.py", line 526, in urlconf_module
    return import_module(self.urlconf_name)
  File "C:\Users\dcrom\AppData\Local\Programs\Python\Python37-32\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\dcrom\PycharmProjects\dgv02\dgv02\urls.py", line 20, in <module>
    path('admin/', admin.site.urls),
  File "C:\Users\dcrom\PycharmProjects\dgv02\venv\lib\site-packages\django\utils\functional.py", line 213, in inner
    self._setup()
  File "C:\Users\dcrom\PycharmProjects\dgv02\venv\lib\site-packages\django\contrib\admin\sites.py", line 526, in _setup
    AdminSiteClass = import_string(apps.get_app_config('admin').default_site)
  File "C:\Users\dcrom\PycharmProjects\dgv02\venv\lib\site-packages\django\apps\registry.py", line 159, in get_app_config
    raise LookupError(message)
LookupError: No installed app with label 'admin'.

**Comment by faramarza** [comment]
never mind found out the issue... thanks
