### ISSUE TITLE
problem with install_labels 

### ISSUE THREAD

**Issue by alhassanha** [neo4j-contrib/django-neomodel#41]
Hi,
I just created my model classes but I'm still stuck at the very first step which is calling "python manage.py install_labels"
it seems that there's a problem with the variable MAX_BOOL_SIZE in neomodel.config, which I searched for but found "MAX_CONNECTION_POOL_SIZE" instead.
anyway I'm using:
- python 3.7
- django 3.1.1
- neo4j 4.1.1
- neomodel 4.0.1
- django-neomodel 0.0.4

here's the error I get:
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\Alhassan\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "C:\Users\Alhassan\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\management\__init__.py", line 377, in execute
    django.setup()
  File "C:\Users\Alhassan\AppData\Local\Programs\Python\Python37\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\Alhassan\AppData\Local\Programs\Python\Python37\lib\site-packages\django\apps\registry.py", line 122, in populate
    app_config.ready()
  File "C:\Users\Alhassan\AppData\Local\Programs\Python\Python37\lib\site-packages\django_neomodel\apps.py", line 20, in ready
    self.read_settings()
  File "C:\Users\Alhassan\AppData\Local\Programs\Python\Python37\lib\site-packages\django_neomodel\apps.py", line 17, in read_settings
    config.MAX_POOL_SIZE = getattr(settings, 'NEOMODEL_MAX_POOL_SIZE', config.MAX_POOL_SIZE)
AttributeError: module 'neomodel.config' has no attribute 'MAX_POOL_SIZE'

**Comment by alhassanha** [comment]
I downgraded neomodel to 3.3 and it worked. never mind and thanks :)
