### ISSUE TITLE
[BUG] ServiceUnavailable: The Neo4J server does not support communication with this driver

### ISSUE THREAD

**Issue by 100gle** [neo4j-contrib/django-neomodel#52]
My Neo4j is `3.4.5` community edition, but when I try to use it to integrate with `Django`, raise this：

```
Traceback (most recent call last):
  File "D:\python-envs\neo4j\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\python-envs\neo4j\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Projects\Demo-Labs\ngraph\app01\views.py", line 29, in get_nodes
    return render('index.html', {"nodes": Event.nodes.all()})
  File "D:\python-envs\neo4j\lib\site-packages\neomodel\match.py", line 524, in all
    return self.query_cls(self).build_ast()._execute(lazy)
  File "D:\python-envs\neo4j\lib\site-packages\neomodel\match.py", line 499, in _execute
    results, _ = db.cypher_query(query, self._query_params, resolve_objects=True)
  File "D:\python-envs\neo4j\lib\site-packages\neomodel\util.py", line 34, in wrapper
    _db.set_connection(config.DATABASE_URL)
  File "D:\python-envs\neo4j\lib\site-packages\neomodel\util.py", line 101, in set_connection
    self.driver = GraphDatabase.driver(u.scheme + '://' + hostname,
  File "D:\python-envs\neo4j\lib\site-packages\neo4j\__init__.py", line 183, in driver
    return cls.bolt_driver(parsed.netloc, auth=auth, **config)
  File "D:\python-envs\neo4j\lib\site-packages\neo4j\__init__.py", line 199, in bolt_driver
    raise ServiceUnavailable(str(error)) from error
neo4j.exceptions.ServiceUnavailable: The Neo4J server does not support communication with this driver. This driver have support for Bolt
Protocols dict_keys([Version(3, 0), Version(4, 0), Version(4, 1)])
```

This issue will be resolved when I downgrade `neo4j` from `4.1.x` version to `1.7.6`, but raise `Can't Import SessionExpire from neo4j.exception` exception. 

--------------

My `settings.py`:

```
NEOMODEL_NEO4J_BOLT_URL = 'bolt://<myusername>:<mypassword>@<myip>:7687'
NEOMODEL_SIGNALS = True
```

My `views`:
```
from django_neomodel import DjangoNode
import neomodel
from django.shortcuts import render


class Event(DjangoNode):
    ID = neomodel.IntegerProperty()
    subject = neomodel.StringProperty()

    class Meta:
        app_label = 'test'


def get_nodes(request):
    return render('index.html', {"nodes": Event.nodes.all()})
```

My `index.html` template:

```
<body>
    <div>
    <ul>
        {% for node in nodes %}
            <li> {{ node.ID }} - {{ node.subject }}</li>
        {% endfor %}
    </ul>
    </div>
</body>
```
-----------
my package info:

```
asgiref==3.3.1
atomicwrites==1.4.0
attrs==20.3.0
backcall==0.2.0
certifi==2020.12.5
cffi==1.14.5
chardet==4.0.0
colorama==0.4.4
cryptography==3.4.6
decorator==4.4.2
Django==3.1.7
django-neomodel==0.0.6
djangorestframework==3.12.2
docker==4.4.4
english==2020.7.0
idna==2.10
iniconfig==1.1.1
ipython==7.21.0
ipython-genutils==0.2.0
jedi==0.18.0
monotonic==1.5
neo4j==4.1.0
neo4j-driver==4.1.1
neobolt==1.7.17
neomodel==4.0.2
neotime==1.7.4
packaging==20.9
pansi==2020.7.3
parso==0.8.1
pickleshare==0.7.5
pluggy==0.13.1
prompt-toolkit==2.0.10
py==1.10.0
py2neo==2021.0.1
pycparser==2.20
Pygments==2.8.1
pyparsing==2.4.7
pytest==6.2.2
pytz==2021.1
pywin32==227
requests==2.25.1
Shapely==1.7.1
six==1.15.0
sqlparse==0.4.1
toml==0.10.2
traitlets==5.0.5
urllib3==1.26.3
wcwidth==0.2.5
websocket-client==0.58.0
```

**Comment by whatSocks** [comment]
@100gle support for 3.5 was deprecated, can you try upgrading your Neo4j version?
