### ISSUE TITLE
neo4j.exceptions.CypherSyntaxError

### ISSUE THREAD

**Issue by shoebjoarder** [neo4j-contrib/django-neomodel#79]
I am following the ReadMe file and when running the command `python manage.py install_labels`, it shows the following error:

  ```
Setting up indexes and constraints...
  
  Found django_neomodel.DjangoNode
   ! Skipping class django_neomodel.DjangoNode is abstract
  Found courserecommender.models.book.Book
   + Creating unique constraint for title on label Book for class courserecommender.models.book.Book
  Traceback (most recent call last):
    File "manage.py", line 22, in <module>
      main()
    File "manage.py", line 18, in main
      execute_from_command_line(sys.argv)
    File "C:\Users\shoeb\.virtualenvs\elas-backend-Ec5edh77\lib\site-packages\django\core\management\__init__.py", line 419, in execute_from_command_line
      utility.execute()
    File "C:\Users\shoeb\.virtualenvs\elas-backend-Ec5edh77\lib\site-packages\django\core\management\__init__.py", line 413, in execute
      self.fetch_command(subcommand).run_from_argv(self.argv)
    File "C:\Users\shoeb\.virtualenvs\elas-backend-Ec5edh77\lib\site-packages\django\core\management\base.py", line 354, in run_from_argv
      self.execute(*args, **cmd_options)
    File "C:\Users\shoeb\.virtualenvs\elas-backend-Ec5edh77\lib\site-packages\django\core\management\base.py", line 398, in execute
      output = self.handle(*args, **options)
    File "C:\Users\shoeb\.virtualenvs\elas-backend-Ec5edh77\lib\site-packages\django_neomodel\management\commands\install_labels.py", line 12, in handle
      install_all_labels(stdout=self.stdout)
    File "C:\Users\shoeb\.virtualenvs\elas-backend-Ec5edh77\lib\site-packages\neomodel\core.py", line 163, in install_all_labels
      install_labels(cls, quiet=False, stdout=stdout)
    File "C:\Users\shoeb\.virtualenvs\elas-backend-Ec5edh77\lib\site-packages\neomodel\core.py", line 134, in install_labels
      cls.__label__, db_property))
    File "C:\Users\shoeb\.virtualenvs\elas-backend-Ec5edh77\lib\site-packages\neomodel\util.py", line 35, in wrapper
      return func(self, *args, **kwargs)
    File "C:\Users\shoeb\.virtualenvs\elas-backend-Ec5edh77\lib\site-packages\neomodel\util.py", line 285, in cypher_query
      raise exc_info[1].with_traceback(exc_info[2])
    File "C:\Users\shoeb\.virtualenvs\elas-backend-Ec5edh77\lib\site-packages\neomodel\util.py", line 268, in cypher_query
      response = session.run(query, params)
    File "C:\Users\shoeb\.virtualenvs\elas-backend-Ec5edh77\lib\site-packages\neo4j\work\simple.py", line 220, in run
      self._bookmarks
    File "C:\Users\shoeb\.virtualenvs\elas-backend-Ec5edh77\lib\site-packages\neo4j\work\result.py", line 115, in _run
      self._attach()
    File "C:\Users\shoeb\.virtualenvs\elas-backend-Ec5edh77\lib\site-packages\neo4j\work\result.py", line 204, in _attach
      self._connection.fetch_message()
    File "C:\Users\shoeb\.virtualenvs\elas-backend-Ec5edh77\lib\site-packages\neo4j\io\_common.py", line 187, in inner
      func(*args, **kwargs)
    File "C:\Users\shoeb\.virtualenvs\elas-backend-Ec5edh77\lib\site-packages\neo4j\io\_bolt4.py", line 306, in fetch_message
      response.on_failure(summary_metadata or {})
    File "C:\Users\shoeb\.virtualenvs\elas-backend-Ec5edh77\lib\site-packages\neo4j\io\_common.py", line 245, in on_failure
      raise Neo4jError.hydrate(**metadata)
  neo4j.exceptions.CypherSyntaxError: {code: Neo.ClientError.Statement.SyntaxError} {message: Invalid constraint syntax, ON and ASSERT should not be used. Replace ON with FOR and ASSERT with REQUIRE. (line 1, column 1 (offset: 0))
  "CREATE CONSTRAINT on (n:Book) ASSERT n.title IS UNIQUE"
   ^}
```
I am running Windows, Neo4j Server version 5.5.0 (community). What is causing this issue?

**Comment by shoebjoarder** [comment]
The `install_labels` function in the `core.py` file under `neomodel` module needs to be updated. I have marked the line with `old version` and my version `new version`. Please have a look at them, if this is need to be updated in the `neomodel` module, because this fix is urgent.

```
def install_labels(cls, quiet=True, stdout=None):
    ...
    for name, property in cls.defined_properties(aliases=False, rels=False).items():
        db_property = property.db_property or name
        if property.index:
            if not quiet:
                stdout.write(' + Creating index {0} on label {1} for class {2}.{3}\n'.format(
                    name, cls.__label__, cls.__module__, cls.__name__))
            try:
                # db.cypher_query("CREATE INDEX on :{0}({1}); ".format(             # old version
                db.cypher_query("CREATE INDEX FOR (n:{0}) ON (n.{1})".format(       # new version
                    cls.__label__, db_property))
            except ClientError as e:
                if e.code in ('Neo.ClientError.Schema.EquivalentSchemaRuleAlreadyExists',
                              'Neo.ClientError.Schema.IndexAlreadyExists'):
                    stdout.write('{0}\n'.format(str(e)))
                else:
                    raise

        elif property.unique_index:
            if not quiet:
                stdout.write(' + Creating unique constraint for {0} on label {1} for class {2}.{3}\n'.format(
                    name, cls.__label__, cls.__module__, cls.__name__))
            try:
                # db.cypher_query("CREATE CONSTRAINT on (n:{0}) ASSERT n.{1} IS UNIQUE".format(             # old version
                db.cypher_query("CREATE CONSTRAINT {1} FOR (n:{0}) REQUIRE n.{1} IS UNIQUE".format(         # new version
                    cls.__label__, db_property))
            except ClientError as e:
                if e.code in ('Neo.ClientError.Schema.EquivalentSchemaRuleAlreadyExists',
                              'Neo.ClientError.Schema.ConstraintAlreadyExists'):
                    stdout.write('{0}\n'.format(str(e)))
                else:
                    raise
```

**Comment by mariusconjeaud** [comment]
Hello @shoebjoarder this is because the current version of django_neomodel targets an older version of neomodel (there wasn't any update for a couple years).

I created two new branches :

- rc/0.0.8 => Extends support to Neo4j version 4.4 => this will become package version 0.0.8 but won't fix your issue yet
- rc/0.1.0 => Extends support to Neo4j version **5.x** => this will become package version 0.1.0 and will fix your issue
