### ISSUE TITLE
Setting admin interrupting runserver on Django 4.x

### ISSUE THREAD

**Issue by anuj9196** [neo4j-contrib/django-neomodel#87]
## Expected Behavior (Mandatory)
Admin panel not working

## Actual Behavior (Mandatory)
The admin panel should work as explained in the doc

## How to Reproduce the Problem
* Install Django 4.x
* Install this plugin (installs 0.0.7)
* Setup node and admin
* Run server

### Simple Example

Datasets and Statements

## Screenshots (where it's possible)
<img width="996" alt="Screenshot 2023-06-21 at 10 49 40 PM" src="https://github.com/neo4j-contrib/django-neomodel/assets/6560085/89936ee9-ab29-49a4-b03d-7140b6ba9ad5">

## Specifications (Mandatory)

Currently used versions

### Versions

  - neo4j-driver: 4.4.10
  - neobolt: 1.7.17
  - neomodel: 5.0.1
  - django-neomodel: 0.0.7
  - Django: 4.2.2

**Comment by codemmmmm** [comment]
Maybe doing the [thing that is required for forms](https://github.com/neo4j-contrib/django-neomodel#model-forms) works, at least that is how I seem to have done it. (And make sure you are really using Django 4)

**Comment by anuj9196** [comment]
Using `DjangoNode` instead of `StructuredNode` is working and this error is no longer coming. However, it has not started giving error
```
'Q' object is not subscriptable
```
traceback
```
originor__dev__app       | Traceback (most recent call last):
originor__dev__app       |   File "/usr/local/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
originor__dev__app       |     response = get_response(request)
originor__dev__app       |   File "/usr/local/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
originor__dev__app       |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
originor__dev__app       |   File "/usr/local/lib/python3.13/site-packages/django/contrib/admin/options.py", line 718, in wrapper
originor__dev__app       |     return self.admin_site.admin_view(view)(*args, **kwargs)
originor__dev__app       |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
originor__dev__app       |   File "/usr/local/lib/python3.13/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
originor__dev__app       |     result = _process_exception(request, e)
originor__dev__app       |   File "/usr/local/lib/python3.13/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
originor__dev__app       |     response = view_func(request, *args, **kwargs)
originor__dev__app       |   File "/usr/local/lib/python3.13/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
originor__dev__app       |     response = view_func(request, *args, **kwargs)
originor__dev__app       |   File "/usr/local/lib/python3.13/site-packages/django/contrib/admin/sites.py", line 241, in inner
originor__dev__app       |     return view(request, *args, **kwargs)
originor__dev__app       |   File "/usr/local/lib/python3.13/site-packages/django/utils/decorators.py", line 48, in _wrapper
originor__dev__app       |     return bound_method(*args, **kwargs)
originor__dev__app       |   File "/usr/local/lib/python3.13/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
originor__dev__app       |     result = _process_exception(request, e)
originor__dev__app       |   File "/usr/local/lib/python3.13/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
originor__dev__app       |     response = view_func(request, *args, **kwargs)
originor__dev__app       |   File "/usr/local/lib/python3.13/site-packages/django/contrib/admin/options.py", line 2001, in changelist_view
originor__dev__app       |     cl = self.get_changelist_instance(request)
originor__dev__app       |   File "/usr/local/lib/python3.13/site-packages/django/contrib/admin/options.py", line 866, in get_changelist_instance
originor__dev__app       |     return ChangeList(
originor__dev__app       |         request,
originor__dev__app       |     ...<12 lines>...
originor__dev__app       |         self.search_help_text,
originor__dev__app       |     )
originor__dev__app       |   File "/usr/local/lib/python3.13/site-packages/django/contrib/admin/views/main.py", line 146, in __init__
originor__dev__app       |     self.get_results(request)
originor__dev__app       |     ~~~~~~~~~~~~~~~~^^^^^^^^^
originor__dev__app       |   File "/usr/local/lib/python3.13/site-packages/django/contrib/admin/views/main.py", line 313, in get_results
originor__dev__app       |     result_count = paginator.count
originor__dev__app       |                    ^^^^^^^^^^^^^^^
originor__dev__app       |   File "/usr/local/lib/python3.13/site-packages/django/utils/functional.py", line 47, in __get__
originor__dev__app       |     res = instance.__dict__[self.name] = self.func(instance)
originor__dev__app       |                                          ~~~~~~~~~^^^^^^^^^^
originor__dev__app       |   File "/usr/local/lib/python3.13/site-packages/django/core/paginator.py", line 110, in count
originor__dev__app       |     return c()
originor__dev__app       |   File "/usr/local/lib/python3.13/site-packages/django_neomodel/__init__.py", line 176, in count
originor__dev__app       |     return len(self)
originor__dev__app       |   File "/usr/local/lib/python3.13/site-packages/neomodel/sync_/match.py", line 819, in __len__
originor__dev__app       |     ast = self.query_cls(self).build_ast()
originor__dev__app       |   File "/usr/local/lib/python3.13/site-packages/neomodel/sync_/match.py", line 433, in build_ast
originor__dev__app       |     self.build_source(self.node_set)
originor__dev__app       |     ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
originor__dev__app       |   File "/usr/local/lib/python3.13/site-packages/neomodel/sync_/match.py", line 459, in build_source
originor__dev__app       |     self.build_where_stmt(
originor__dev__app       |     ~~~~~~~~~~~~~~~~~~~~~^
originor__dev__app       |         ident,
originor__dev__app       |         ^^^^^^
originor__dev__app       |     ...<2 lines>...
originor__dev__app       |         source_class=source.source_class,
originor__dev__app       |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
originor__dev__app       |     )
originor__dev__app       |     ^
originor__dev__app       |   File "/usr/local/lib/python3.13/site-packages/neomodel/sync_/match.py", line 657, in build_where_stmt
originor__dev__app       |     stmts = self._parse_q_filters(ident, q_filters, source_class)
originor__dev__app       |   File "/usr/local/lib/python3.13/site-packages/neomodel/sync_/match.py", line 623, in _parse_q_filters
originor__dev__app       |     q_childs = self._parse_q_filters(ident, child, source_class)
originor__dev__app       |   File "/usr/local/lib/python3.13/site-packages/neomodel/sync_/match.py", line 628, in _parse_q_filters
originor__dev__app       |     kwargs = {child[0]: child[1]}
originor__dev__app       |               ~~~~~^^^
originor__dev__app       | TypeError: 'Q' object is not subscriptable

```

**Comment by HlebKrah** [comment]
Same for me on django 5.2

**Comment by koking0** [comment]
+1

**Comment by shifenhutu** [comment]
same here   django 5.2.1

**Comment by qinyanjuidavid** [comment]
was  the error "TypeError: 'Q' object is not subscriptable" solved?

**Comment by curious-broccoli** [comment]
> was the error "TypeError: 'Q' object is not subscriptable" solved?

There has been no commits in two years, the project is dead.
