### ISSUE TITLE
i can't install the package 

### ISSUE THREAD

**Issue by bydevmar** [neo4j-contrib/django-neomodel#97]
$ pip install django_neomodel
Collecting django_neomodel
  Using cached django_neomodel-0.1.1-py3-none-any.whl.metadata (8.1 kB)
Collecting neomodel~=5.1.0 (from django_neomodel)
  Using cached neomodel-5.1.2-py3-none-any.whl.metadata (6.1 kB)
Requirement already satisfied: django>=2.2 in c:\users\bydevmar\appdata\local\programs\python\python312\lib\site-packages (from django_neomodel) (5.0.3)
Requirement already satisfied: asgiref<4,>=3.7.0 in c:\users\bydevmar\appdata\local\programs\python\python312\lib\site-packages (from django>=2.2->django_neomodel) (3.8.1)
Requirement already satisfied: sqlparse>=0.3.1 in c:\users\bydevmar\appdata\local\programs\python\python312\lib\site-packages (from django>=2.2->django_neomodel) (0.4.4)
Requirement already satisfied: tzdata in c:\users\bydevmar\appdata\local\programs\python\python312\lib\site-packages (from django>=2.2->django_neomodel) (2024.1)
Collecting neo4j==5.12.0 (from neomodel~=5.1.0->django_neomodel)
  Using cached neo4j-5.12.0.tar.gz (190 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  error: subprocess-exited-with-error

  Getting requirements to build wheel did not run successfully.
  exit code: 1

  [33 lines of output]
  Traceback (most recent call last):
    File "C:\Users\BYDEVMAR\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
      main()
    File "C:\Users\BYDEVMAR\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\BYDEVMAR\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 112, in get_requires_for_build_wheel
      backend = _build_backend()
                ^^^^^^^^^^^^^^^^
    File "C:\Users\BYDEVMAR\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 77, in _build_backend
      obj = import_module(mod_path)
            ^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\BYDEVMAR\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
    File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
    File "<frozen importlib._bootstrap>", line 1304, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
    File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
    File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
    File "<frozen importlib._bootstrap>", line 1325, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 929, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 994, in exec_module
    File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
    File "C:\Users\BYDEVMAR\AppData\Local\Temp\pip-build-env-zp73pyfh\overlay\Lib\site-packages\setuptools\__init__.py", line 16, in <module>
      import setuptools.version
    File "C:\Users\BYDEVMAR\AppData\Local\Temp\pip-build-env-zp73pyfh\overlay\Lib\site-packages\setuptools\version.py", line 1, in <module>
      import pkg_resources
    File "C:\Users\BYDEVMAR\AppData\Local\Temp\pip-build-env-zp73pyfh\overlay\Lib\site-packages\pkg_resources\__init__.py", line 2191, in <module>
      register_finder(pkgutil.ImpImporter, find_on_path)
                      ^^^^^^^^^^^^^^^^^^^
  AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

Getting requirements to build wheel did not run successfully.
exit code: 1

See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by mariusconjeaud** [comment]
This looks like you are trying to import this with Python 3.12, which was not supported by neomodel 5.1.0

Try the new version 0.1.2, which bumps neomodel to 5.3.0, which supports Python 3.12
